# https://alacritty.org/config-alacritty.html

import = ["~/.config/alacritty/alacritty-bindings.toml", "~/.config/alacritty/theme-current.toml"]

live_config_reload = true

[env]
    term = "xterm-256color"
    #term = "alacritty"

[window]
    padding = { x = 10, y = 10 }
    dynamic_padding = true
    decorations = "buttonless"
    opacity = 1
    startup_mode = "Maximized"
    decorations_theme_variant = "Dark"

[scrolling]
    history = 100000
    multiplier = 3

[font]
    # brew install font-hack-nerd-font
    size = 12
    # offset.y = 5
    offset.x = 0
    normal.family = "Hack Nerd Font"
    normal.style = "Regular"
    bold.family = "Hack Nerd Font"
    bold.style = "Bold"
    italic.family = "Hack Nerd Font"
    italic.style = "Italic"

[selection]
    save_to_clipboard = false
    semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
    style.shape = "Beam"
    style.blinking = "On"
    blink_interval = 300
    blink_timeout = 20

[[hints.enabled]]
    regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\\s]+"
    hyperlinks = true
    command = "open"
    [hints.enabled.mouse]
        enabled = true

[debug]
    render_timer = false
    print_events = true
