# https://alacritty.org/config-alacritty.html

import = [
    "~/.config/alacritty/alacritty-bindings.toml",
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml",
]

live_config_reload = true

[env]
term = "xterm-256color"
# term = "alacritty"

[window]
padding = { x = 10, y = 40 }
dynamic_padding = true
decorations = "transparent"
opacity = 1
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[scrolling]
history = 100000
multiplier = 1

[font]
size = 14
offset.y = 5

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
style.shape = "Block"
style.blinking = "On"
blink_interval = 300
blink_timeout = 20

[[hints.enabled]]
hyperlinks = true
command = "open"

[debug]
render_timer = false
print_events = true
