# # Colors (Gruvbox Material Medium Dark)

# [colors.primary]
#     background = "#303446"
#     foreground = "#c6d0f5"
#     dim_foreground = "#838ba7"
#     bright_foreground = "#c6d0f5"

# [colors.cursor]
#     text = "#303446"
#     cursor = "#f2d5cf"

# [colors.vi_mode_cursor]
#     text = "#303446"
#     cursor = "#babbf1"

# [colors.search.matches]
#     foreground = "#303446"
#     background = "#a5adce"

# [colors.search.focused_match]
#     foreground = "#303446"
#     background = "#a6d189"

# [colors.footer_bar]
#     foreground = "#303446"
#     background = "#a5adce"

# [colors.hints.start]
#     foreground = "#303446"
#     background = "#e5c890"

# [colors.hints.end]
#     foreground = "#303446"
#     background = "#a5adce"

# [colors.selection]
#     text = "#303446"
#     background = "#f2d5cf"

# [colors.normal]
#     black = "#51576d"
#     red = "#e78284"
#     green = "#a6d189"
#     yellow = "#e5c890"
#     blue = "#8caaee"
#     magenta = "#f4b8e4"
#     cyan = "#81c8be"
#     white = "#b5bfe2"

# [colors.bright]
#     black = "#626880"
#     red = "#e78284"
#     green = "#a6d189"
#     yellow = "#e5c890"
#     blue = "#8caaee"
#     magenta = "#f4b8e4"
#     cyan = "#81c8be"
#     white = "#a5adce"

# [[colors.indexed_colors]]
#     index = 16
#     color = "#ef9f76"

# [[colors.indexed_colors]]
#     index = 17
#     color = "#f2d5cf"

[colors.primary]
    background = "#2e3440"
    foreground = "#d8dee9"
    dim_foreground = "#a5abb6"

[colors.cursor]
    text = "#2e3440"
    cursor = "#d8dee9"

[colors.vi_mode_cursor]
    text = "#2e3440"
    cursor = "#d8dee9"

[colors.selection]
    text = "CellForeground"
    background = "#4c566a"

[colors.search_matches]
    foreground = "CellBackground"
    background = "#88c0d0"

[colors.search_bar]
    background = "#434c5e"
    foreground = "#d8dee9"

[colors.normal]
    black = "#3b4252"
    red = "#bf616a"
    green = "#a3be8c"
    yellow = "#ebcb8b"
    blue = "#81a1c1"
    magenta = "#b48ead"
    cyan = "#88c0d0"
    white = "#e5e9f0"

[colors.bright]
    black = "#4c566a"
    red = "#bf616a"
    green = "#a3be8c"
    yellow = "#ebcb8b"
    blue = "#81a1c1"
    magenta = "#b48ead"
    cyan = "#8fbcbb"
    white = "#eceff4"

[colors.dim]
    black = "#373e4d"
    red = "#94545d"
    green = "#809575"
    yellow = "#b29e75"
    blue = "#68809a"
    magenta = "#8c738c"
    cyan = "#6d96a5"
    white = "#aeb3bb"
